---
- hosts: all
  tasks:
    - name: Install software
      package:
        name: '{{ packages }}'
        state: present
    - name: Start/enable gdm service
      service:
        name: gdm
        enabled: yes
        state: started
    - name: Check if user already exists
      getent:
        database: passwd
        key: '{{ username }}'
      register: user_check
      ignore_errors: true
    - name: Create user if it not already exists
      user:
        name: '{{ username }}'
        password: '{{ password | password_hash("sha512") }}'
        shell: /bin/bash
        groups: wheel
        append: yes
        state: present
      when: user_check.failed
    - name: Allow group wheel to use sudo
      lineinfile:
        path: /etc/sudoers
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL:ALL) ALL'
        state: present
    - name: Install trizen (git clone)
      git:
        repo: 'https://aur.archlinux.org/trizen.git'
        dest: /root/trizen
